pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'mechmathfan/notejam:latest'
    }

    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t $DOCKER_IMAGE .'
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                script {
                    sh 'docker push $DOCKER_IMAGE'
                }
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                script {
                    sh 'kubectl apply -f db-deployment.yaml'
                    sh 'kubectl apply -f db-service.yaml'
                    sh 'kubectl apply -f web-deployment.yaml'
                    sh 'kubectl apply -f web-service.yaml'
                }
            }
        }
    }

    post {
        success {
            echo 'Deployment successful!'
        }
        failure {
            echo 'Deployment failed.'
        }
    }
}
