apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - image: postgres:latest
          name: database
          env:
            - name: POSTGRES_PASSWORD
              value: "admin123"  # Простий пароль для демонстрації
          ports:
            - containerPort: 5432
